# For vim: set makeprg=gmake\ -f\ Makefile.Msys-gmake

# Work around .c vs .C case insensitivity with Windows and mingw
# The .c file gets assigned to g++ because it matches with the makefile
# rule for .C files.
CXX=$(CC)
CPPFLAGS=$(CFLAGS)

include Makefile.Msys

