include Makefile.msys-mingw32

# Work around .c vs .C case insensitivity with Windows and mingw
# The .c file gets assigned to g++ because it matches with the makefile
# rule for .C files.
CXX=$(CC)
CPPFLAGS=$(CFLAGS)

RM:=del
INSTALL_DIR=$(USERPROFILE)\\bin
INSTALL=copy


